package core

import (
	"io"
	"io/fs"
	"net/http"
	"path"
	"strings"
	"time"
)

// routeAction defines the explicit instruction returned by the URL resolver.
type routeAction int

const (
	actionServe routeAction = iota
	actionRedirect
	actionNotFound
)

// FSHandler is a highly optimized, zero-fallback static file handler designed 
// specifically for Multi-Page Applications (MPAs) and SPAs with dynamic backend routing.
//
// PERFORMANCE GUARANTEE:
// This handler guarantees exactly ONE filesystem Open and ONE filesystem Stat per 
// successful request. It relies on strict conventions and avoids all TOCTOU 
// (Time-of-Check to Time-of-Use) issues and expensive filesystem guesswork.
//
// WHY NOT http.FileServerFS?
// 1. Dynamic Pages: http.FileServerFS strictly maps the HTTP Request URL to the filesystem path. 
//    We need to map dynamic RESTful URLs (e.g., "GET /books/{id}/sentences/{idx}") to specific 
//    static HTML bundles (e.g., "sentence-nlp/index.html").
// 2. Performance: http.FileServerFS performs 2 to 4 filesystem operations (Open, Stat, Stat) 
//    to resolve directories to index.html and handle redirects.
//
// PARAMETERS:
//
//   - fsys (fs.FS):
//     The underlying filesystem, typically an embed.FS or os.DirFS.
//
//   - explicitPath (string): 
//     An optional, strict override. If provided, the handler ignores the request URL 
//     and serves exactly this file. 
//     * Must be a clean, relative path pointing to a FILE, not a directory 
//       (e.g., "about/index.html", not "/about/").
//     * Used for mapping dynamic RESTful URLs (e.g., "GET /users/{id}") to a 
//       specific static frontend bundle.
//
//   - compressionExt (string): 
//     An optional extension generated by your bundler (e.g., ".gz" or ".br").
//     If provided, and the browser's Accept-Encoding supports it, the handler 
//     will append this to the physical path it opens.
//
// URL RESOLUTION CONVENTIONS (Used when explicitPath is empty):
//
//   1. Root Path ("/" or ""): 
//      Always resolves to "index.html".
//   
//   2. Private Paths: 
//      Any file or directory segment starting with an underscore (e.g., "_search", 
//      "components/_hidden.js") is considered private and returns HTTP 404.
//
//   3. Direct Assets (Has Extension): 
//      URLs with a file extension (e.g., "/dist/app.js") map directly to that file.
//
//   4. MPA Routes / Directories (No Extension): 
//      URLs without an extension are assumed to be directory paths. 
//      * Missing Trailing Slash: Returns HTTP 301 Redirect to append the slash, 
//        ensuring browser relative paths (like <img src="./logo.png">) work correctly.
//      * Has Trailing Slash: Appends "index.html" strictly in-memory and serves it.
//
// COMPRESSION & HEADERS RULES:
//
//   - Zero Fallback: If compressionExt is set and the browser supports it, the handler 
//     will ONLY attempt to open the compressed file (e.g., "app.js.gz"). It will not 
//     fall back to "app.js" if the compressed file is missing. 
//   - Exclusions: HTML files (".html", ".htm") are never compressed by this handler.
//   - Content-Type Safety: The Content-Type header is always derived natively from the 
//     logical file extension (e.g., "app.js" -> application/javascript), preventing 
//     browsers from downloading compressed assets as binary "octet-stream" attachments.
//   - Content-Encoding: Automatically sets the proper Content-Encoding and Vary headers.
func FSHandler(fsys fs.FS, explicitPath string, compressionExt string) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		// 0. Method Restriction
		// While http.FileServer automatically blocks POST/PUT/DELETE requests
		// with a 405 Method Not Allowed, http.ServeContent does not.
		if r.Method != http.MethodGet && r.Method != http.MethodHead {
			w.Header().Set("Allow", "GET, HEAD")
			http.Error(w, "Method Not Allowed", http.StatusMethodNotAllowed)
			return
		}

		var action routeAction
		var basePath string

		// 1. Gatekeeper Logic
		if explicitPath != "" {
			action = actionServe
			basePath = explicitPath
		} else {
			action, basePath = resolveURL(r.URL.Path)
		}

		// 2. Execute Routing Instruction
		switch action {
		case actionNotFound:
			http.NotFound(w, r)
			return

		case actionRedirect:
			// Fix the Browser Relative Path Redirection Issue.
			// Preserve query string during the trailing slash redirect.
			redirectURL := r.URL.Path + "/"
			if r.URL.RawQuery != "" {
				redirectURL += "?" + r.URL.RawQuery
			}
			http.Redirect(w, r, redirectURL, http.StatusMovedPermanently)
			return
		}

		// 3. Resolve Compression
		openPath, encodingName := resolveCompression(basePath, compressionExt, r.Header.Get("Accept-Encoding"))

		// 4. Filesystem Operations
		// EXACTLY ONE FS OPEN (No fallback guesswork)
		f, err := fsys.Open(openPath)
		if err != nil {
			http.NotFound(w, r)
			return
		}
		defer func() { _ = f.Close() }()

		// EXACTLY ONE FS STAT 
		stat, err := f.Stat()
		if err != nil || stat.IsDir() {
			http.NotFound(w, r)
			return
		}

		// Type assert the file to a ReadSeeker, which http.ServeContent requires.
		seeker, ok := f.(io.ReadSeeker)
		if !ok {
			http.Error(w, "internal server error", http.StatusInternalServerError)
			return
		}

		// 5. Apply Headers & Serve
		if encodingName != "" {
			w.Header().Set("Content-Encoding", encodingName)
			w.Header().Set("Vary", "Accept-Encoding")
		}

		// Using time.Time{} (zero time) as modTime is a deliberate optimization:
		// - Embedded assets are immutable - they don't change after compilation
		// - The modification time is irrelevant since the content is fixed
		// It prevents the header from being set, so the client never sends If-Modified-Since in the first place.
		//   * Reduces server-side processing overhead
        //
		// CRITICAL: We pass `basePath` (e.g. "app.js") to ServeContent, NOT `openPath`. 
		// http.ServeContent automatically sets Content-Type based on:
		// 1. The file extension in the path parameter (r.URL.Path)
		// 2. If extension is unknown, it sniffs the first 512 bytes of content
		// This forces Go to automatically set Content-Type: application/javascript instead 
		// of sniffing binary data and setting octet-stream.
		http.ServeContent(w, r, basePath, time.Time{}, seeker)
	}
}

// resolveURL translates a raw URL path into an actionable routing command 
// and a base filesystem path.
func resolveURL(requestPath string) (routeAction, string) {
	cleanPath := strings.TrimPrefix(path.Clean(requestPath), "/")

	// PRIVATE PATH RULE: If any segment starts with an underscore, it is forbidden.
	if strings.HasPrefix(cleanPath, "_") || strings.Contains(cleanPath, "/_") {
		return actionNotFound, ""
	}

	// ROOT RULE: Always maps to index.html
	if cleanPath == "" || cleanPath == "." {
		return actionServe, "index.html"
	}

	// EXTENSION RULE: If it has an extension, treat it as a direct asset request
	if path.Ext(cleanPath) != "" {
		return actionServe, cleanPath
	}

	// MPA ROUTE RULE (No Extension):
	if !strings.HasSuffix(requestPath, "/") {
		return actionRedirect, ""
	}

	return actionServe, cleanPath + "/index.html"
}

// resolveCompression determines if a compressed version of the file should be served.
// It returns the physical path to open, and the Content-Encoding header value to set.
func resolveCompression(basePath, compressionExt, acceptEncoding string) (openPath string, encodingName string) {
	if compressionExt == "" {
		return basePath, ""
	}

	// Never compress HTML files
	if strings.HasSuffix(basePath, ".html") || strings.HasSuffix(basePath, ".htm") {
		return basePath, ""
	}

	// Map standard extensions to HTTP encoding names
	if compressionExt == ".gz" {
		encodingName = "gzip"
	} else if compressionExt == ".br" {
		encodingName = "br"
	} else {
		// Unknown compression extension
		return basePath, ""
	}

	// Check if the browser actually supports this encoding
	if strings.Contains(acceptEncoding, encodingName) {
		return basePath + compressionExt, encodingName
	}

	return basePath, ""
}
