package core

import (
	"errors"
	"fmt"
	"net/http"
	"net/mail"
	"strings"
)

// Validator defines an interface for request validation operations
type Validator interface {
	// ContentType checks if the request's Content-Type matches the allowed type
	ContentType(r *http.Request, allowedType string) (jsonResponse, error)

	// Email checks if an email address is valid according to RFC 5321/5322.
	// It rejects display-name formats ("Name <addr>"), enforces length limits,
	// and ensures the domain has a valid structure.
	Email(email string) error

	// Password checks a password against NIST SP 800-63B guidelines.
	// It enforces length bounds and rejects known-compromised passwords.
	// It deliberately avoids complexity rules (uppercase/number/symbol
	// requirements), which reduce entropy in practice.
	Password(password string) error
}

// DefaultValidator implements the Validator interface
type DefaultValidator struct{}

// NewValidator creates a new DefaultValidator instance
func NewValidator() Validator {
	return &DefaultValidator{}
}

// ContentType checks if the request's Content-Type matches the allowed type.
// Returns:
// - error (always "Invalid content type" for security)
// - precomputed jsonResponse for error cases
// Uses http.StatusUnsupportedMediaType (415) for invalid content types as per HTTP spec.
func (v *DefaultValidator) ContentType(r *http.Request, allowedType string) (jsonResponse, error) {
	errInvalidType := errors.New("invalid content type")
	contentType := r.Header.Get("Content-Type")
	if contentType == "" {
		return errorInvalidContentType, errInvalidType
	}

	// Handle cases where Content-Type includes charset or other parameters
	// e.g. "application/json; charset=utf-8"
	mediaType := strings.Split(contentType, ";")[0]
	mediaType = strings.TrimSpace(mediaType)

	if mediaType != allowedType {
		return errorInvalidContentType, errInvalidType
	}

	return jsonResponse{}, nil
}

// Email checks if an email address is valid according to RFC 5321/5322.
// It rejects display-name formats ("Name <addr>"), enforces length limits,
// and ensures the domain has a valid structure.
func (v *DefaultValidator) Email(email string) error {
	// RFC 5321: max total length is 254 characters
	if len(email) > 254 {
		return fmt.Errorf("email address exceeds 254 character limit")
	}

	// mail.ParseAddress accepts "Display Name <user@host>" — we reject that.
	// A bare email must round-trip: parsed address must equal the input exactly.
	addr, err := mail.ParseAddress(email)
	if err != nil {
		return fmt.Errorf("invalid email format: %w", err)
	}
	if addr.Address != email {
		return fmt.Errorf("invalid email format: display name or angle brackets are not allowed")
	}

	// Split into local and domain parts for further checks.
	// mail.ParseAddress already guarantees exactly one '@' at this point.
	at := strings.LastIndex(email, "@")
	localPart := email[:at]
	domain := email[at+1:]

	// RFC 5321: local part must not exceed 64 characters
	if len(localPart) > 64 {
		return fmt.Errorf("email local part exceeds 64 character limit")
	}

	// Domain must contain at least one dot and no empty labels.
	// Rejects: "user@localhost", "user@.com", "user@com."
	if !strings.Contains(domain, ".") {
		return fmt.Errorf("email domain must contain at least one dot")
	}
	for _, label := range strings.Split(domain, ".") {
		if label == "" {
			return fmt.Errorf("email domain contains an empty label")
		}
	}

	return nil
}

// Password checks a password against NIST SP 800-63B guidelines.
func (v *DefaultValidator) Password(password string) error {
	const (
		minLength = 8
		// bcrypt silently truncates input at 72 bytes. A password longer than
		// this would hash identically to its 72-byte prefix, giving a false
		// sense of security. We measure bytes, not runes, for the same reason
		// bcrypt does.
		maxBytes = 72
	)

	if len(password) < minLength {
		return fmt.Errorf("password must be at least %d characters", minLength)
	}

	if len([]byte(password)) > maxBytes {
		return fmt.Errorf("password must not exceed %d bytes", maxBytes)
	}

	// Null bytes are not printable and break many downstream systems silently.
	if strings.ContainsRune(password, 0) {
		return fmt.Errorf("password must not contain null bytes")
	}

	// NIST 800-63B §5.1.1: check against known-compromised passwords.
	// The list is generated by scripts/gen_passwords.go and committed as
	// core/common_passwords_gen.go — it is never fetched at runtime.
	if isCommonPassword(password) {
		return fmt.Errorf("password is too common or has appeared in known data breaches — please choose a different one")
	}

	return nil
}

// isCommonPassword reports whether the password appears in the known-compromised
// list. Comparison is case-insensitive: "Password1" is as weak as "password1".
// TODO 
//
//var commonPasswords = map[string]struct{}{
//	"password":         {},
//	"12345678":         {},
//	"123456789":        {},
//	"baseball":         {},
//	"football":         {},
//	"qwertyuiop":       {},
//	"1234567890":       {},
func isCommonPassword(password string) bool {
	//_, found := commonPasswords[strings.ToLower(password)]
	//return found
    return false
}
