package config

import (
	"testing"
)

// TestNewDefaultConfig_IsValid ensures that the configuration generated by
// NewDefaultConfig() is valid according to the Validate function. This is a
// critical check to ensure the application can start with its default settings.
func TestNewDefaultConfig_IsValid(t *testing.T) {

	// Create a new default configuration.
	cfg := NewDefaultConfig()

	// The default configuration should always be valid.
	if err := Validate(cfg); err != nil {
		t.Fatalf("NewDefaultConfig() produced an invalid configuration: %v", err)
	}
}
