package config

import (
	"testing"
	"time"
)

// TestNewDefaultConfig_IsValid ensures that the configuration generated by
// NewDefaultConfig() is valid according to the Validate function. This is a
// critical check to ensure the application can start with its default settings.
func TestNewDefaultConfig_IsValid(t *testing.T) {

	// Create a new default configuration.
	cfg := NewDefaultConfig()

	// The default configuration should always be valid.
	if err := Validate(cfg); err != nil {
		t.Fatalf("NewDefaultConfig() produced an invalid configuration: %v", err)
	}
}

func TestNewBackupLocalDbFileDefaults(t *testing.T) {
	v := NewBackupLocalDbFileDefaults()
	if v.SourcePath != "" {
		t.Errorf("SourcePath: got %q, want empty", v.SourcePath)
	}
	if v.Strategy != BackupStrategyOnline {
		t.Errorf("Strategy: got %q, want %q", v.Strategy, BackupStrategyOnline)
	}
	if v.Compression != false {
		t.Errorf("Compression: got %v, want false", v.Compression)
	}
	if v.Frequency.Duration != 15*time.Minute {
		t.Errorf("Frequency: got %v, want 15m", v.Frequency)
	}
}

func TestNewOAuth2ProviderDefaults(t *testing.T) {
	v := NewOAuth2ProviderDefaults()
	if v.Name != "" {
		t.Errorf("Name: got %q, want empty", v.Name)
	}
	if v.ClientID != "" {
		t.Errorf("ClientID: got %q, want empty", v.ClientID)
	}
	if v.ClientSecret != "" {
		t.Errorf("ClientSecret: got %q, want empty", v.ClientSecret)
	}
	if v.PKCE != true {
		t.Errorf("PKCE: got %v, want true", v.PKCE)
	}
}
