// gen_passwords.go generates core/common_passwords_gen.go from a public breach
// password list, keeping only entries that could pass the minimum length check.
//
// Usage (from repo root):
//
//	go run scripts/gen_passwords.go

package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"net/http"
	"os"
	"strings"
	"text/template"
)

const (
    //sourceURL  = "https://raw.githubusercontent.com/danielmiessler/SecLists/refs/heads/master/Passwords/Common-Credentials/100k-most-used-passwords-NCSC.txt"
    //sourceURL  = "https://raw.githubusercontent.com/danielmiessler/SecLists/refs/heads/master/Passwords/Common-Credentials/Pwdb_top-100000.txt"
    //sourceURL  = "https://raw.githubusercontent.com/danielmiessler/SecLists/refs/heads/master/Passwords/Common-Credentials/xato-net-10-million-passwords-100000.txt"
    sourceURL  = "https://raw.githubusercontent.com/danielmiessler/SecLists/refs/heads/master/Passwords/Common-Credentials/xato-net-10-million-passwords-10000.txt"
	outputFile = "core/common_passwords_gen.go"
	outputPkg  = "core"

	// Must match the minLength constant in core/validation.go.
	// Passwords shorter than this are rejected before isCommonPassword is ever
	// reached, so storing them wastes memory with no benefit.
	minLength = 8
)

var fileTemplate = template.Must(template.New("").Parse(`// Code generated by scripts/gen_passwords.go. DO NOT EDIT.
// Source: {{.Source}}
package {{.Package}}

var commonPasswords = map[string]struct{}{
{{- range .Passwords}}
	{{printf "%q" .}}: {},
{{- end}}
}
`))

func main() {
	fmt.Println("Fetching password list from SecLists...")

	resp, err := http.Get(sourceURL)
	if err != nil {
		fmt.Fprintf(os.Stderr, "fetch failed: %v\n", err)
		os.Exit(1)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		fmt.Fprintf(os.Stderr, "unexpected status: %s\n", resp.Status)
		os.Exit(1)
	}

	var (
		passwords    []string
		totalScanned int
		skippedShort int
		duplicates   int
	)

	seen := make(map[string]struct{})

	scanner := bufio.NewScanner(resp.Body)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		totalScanned++
		lower := strings.ToLower(line)

		if len(lower) < minLength {
			skippedShort++
			continue
		}

		if _, ok := seen[lower]; ok {
			duplicates++
			continue
		}

		seen[lower] = struct{}{}
		passwords = append(passwords, lower)
	}
	if err := scanner.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "reading response: %v\n", err)
		os.Exit(1)
	}

	var buf bytes.Buffer
	if err := fileTemplate.Execute(&buf, map[string]any{
		"Source":    sourceURL,
		"Package":   outputPkg,
		"Passwords": passwords,
	}); err != nil {
		fmt.Fprintf(os.Stderr, "template error: %v\n", err)
		os.Exit(1)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "gofmt error: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write error: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf(
		"Done. %d/%d passwords written to %s (skipped %d under %d chars, %d duplicates)\n",
		len(passwords),
		totalScanned,
		outputFile,
		skippedShort,
		minLength,
		duplicates,
	)
}
