package crypto

import (
	"crypto/hmac"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
)

// ====================================================================================
// STATELSS GATEKEEPER (HMAC)
// These functions prevent Timing-Based User Enumeration and bypass expensive DB lookups 
// Authenticate()
// ====================================================================================

// GenerateUserMac creates a fast, stateless cryptographic proof that a user_id
// was generated by this server. We truncate the hex output to 16 characters (64 bits).
// 64 bits is plenty for online-only HTTP verification and keeps the JWT payload small.
func GenerateUserMac(userID string, serverSecret string) string {
	h := hmac.New(sha256.New, []byte(serverSecret))
	h.Write([]byte(userID))
	
	// Encode to hex and truncate to 16 chars (8 bytes / 64 bits of entropy)
	fullHex := hex.EncodeToString(h.Sum(nil))
	return fullHex[:16] 
}

// VerifyUserMac checks if the provided MAC matches the userID.
// CRITICAL: Uses subtle.ConstantTimeCompare to prevent timing attacks on the MAC itself.
func VerifyUserMac(userID, providedMac, serverSecret string) bool {
	// 1. Instantly reject missing or badly formatted MACs
	if len(providedMac) != 16 {
		return false
	}

	// 2. Calculate the expected MAC
	expectedMac := GenerateUserMac(userID, serverSecret)

	// 3. Constant-time comparison
	// Returns 1 if slices match, 0 if they don't
	return subtle.ConstantTimeCompare([]byte(providedMac), []byte(expectedMac)) == 1
}
