name: sloc

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sloc-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install scc and jq
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          go install github.com/boyter/scc/v3@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run scc and format line count
        run: |
          scc --format json --output scc.json .
          LINES_OF_CODE=$(jq 'map(.Code) | add' scc.json)
          # Format the number, e.g., 11290 -> 11k, ensuring no decimals or spaces
          FORMATTED_LINES=$(awk -v lines="$LINES_OF_CODE" 'BEGIN {if (lines >= 1000) {printf "%.0fk", lines/1000} else {print lines}}')
          echo "LINES_OF_CODE=$LINES_OF_CODE" >> $GITHUB_ENV
          echo "FORMATTED_LINES=$FORMATTED_LINES" >> $GITHUB_ENV

      - name: Generate SLOC badge
        run: |
          # Create badge directory
          mkdir -p .github/badges

          # Generate SVG badge using the same conventions as the coverage badge
          cat > .github/badges/sloc.svg << EOF
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="110" height="20" role="img" aria-label="total lines: ${{ env.FORMATTED_LINES }}">
            <title>total lines: ${{ env.FORMATTED_LINES }}</title>
            <linearGradient id="s" x2="0" y2="100%">
              <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
              <stop offset="1" stop-opacity=".1"/>
            </linearGradient>
            <clipPath id="r">
              <rect width="110" height="20" rx="3" fill="#fff"/>
            </clipPath>
            <g clip-path="url(#r)">
              <rect width="73" height="20" fill="#555"/>
              <rect x="73" width="37" height="20" fill="#4c1"/>
              <rect width="110" height="20" fill="url(#s)"/>
            </g>
            <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110">
              <text aria-hidden="true" x="375" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="630">total lines</text>
              <text x="375" y="140" transform="scale(.1)" fill="#fff" textLength="630">total lines</text>
              <text aria-hidden="true" x="905" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="270">${{ env.FORMATTED_LINES }}</text>
              <text x="905" y="140" transform="scale(.1)" fill="#fff" textLength="270">${{ env.FORMATTED_LINES }}</text>
            </g>
          </svg>
          EOF

      - name: Commit SLOC badge
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          if git diff --quiet HEAD -- .github/badges/sloc.svg; then
            echo "No changes to SLOC badge"
          else
            git add .github/badges/sloc.svg
            git commit -m "Update total lines badge: ${{ env.LINES_OF_CODE }}"
            git push
          fi
